judo_school/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers
from judo_quiz_api import views


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
# urlpatterns = [
#     path('', include(router.urls)),
#     path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<int:techniques_id>/', views.detail, name='detail'),
    path('<int:techniques_id>/vote/', views.vote, name='vote'),
]

judo_quiz_api/models.py
from django.db import models

# Create your models here.

quiz/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage

photosPath = FileSystemStorage(location='/media/photos')

class Techniques(models.Model):
    name = models.CharField(max_length=200)
    belt_group = models.ForeignKey('Belt_group', on_delete=models.CASCADE)
    photo = models.ImageField(null=True)
    def __str__(self):
        return self.name

    def photo_name(self):
        return self.photo
    

class Belt_group(models.Model):
    belt_color = models.CharField(max_length=200)
    def __str__(self):
        return self.belt_color

judo_quiz_api/views.py
from django.shortcuts import render

from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from judo_quiz_api.serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

quiz/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic

from .models import Techniques, Belt_group

class IndexView(generic.ListView):
    template_name = 'quiz/index.html'
    context_object_name = 'latest_technic_list'

    def get_queryset(self):
        """Return the last five technics"""
        return Techniques.objects.order_by('belt_group')



def detail(request, techniques_id):
    try:
        technic = Techniques.objects.get(pk=techniques_id)
        belts = Belt_group.objects.all()
    except Techniques.DoesNotExist:
        raise Http404("technic does not exist")
    return render(request, 'quiz/detail.html', {'technic': technic, 'belts': belts})


def vote(request, techniques_id):

    technic = Techniques.objects.get(pk=techniques_id)
    right_belt_color = get_object_or_404(Belt_group, pk=technic.belt_group_id)

    response = "No, it was technic from: %s belt."
    if str(request.POST['selected_belt']) == str(right_belt_color):
        response = "Nice! That's right it is %s"
    return HttpResponse(response % right_belt_color)

quiz/templates/quiz/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}">

<h1>{{ technic.name }}</h1>

<img class="technic-image" src="/static/images/{{technic.photo}}"> {% if error_message %}
<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="content">
    <form action="{% url 'quiz:vote' technic.id %}" method="post">
        {% csrf_token %}
        <p> Which belt is it?</p>
        {% for belt in belts %}
        <input type="radio" name="selected_belt" id="{{belt.id}}" value="{{ belt.belt_color }}">
        <label for="belt{{ belt.id }}">{{ belt.belt_color }}</label><br> {% endfor %}<br>
        <input type="submit" value="Vote">
    </form>
</div>

quiz/templates/quiz/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}">

<!--  -->
<h1>Judo technics</h1>
{% if latest_technic_list %}
<ul>
    {% for technic in latest_technic_list %}
    <!-- <li><a href="/quiz/{{ technic.id }}/">{{ technic.name }}</a></li> -->
    <li><a href="{% url 'quiz:detail' technic.id %}">{{ technic.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No technics are available.</p>
{% endif %}